-- personnel_user table structure and seed data
-- Source: current in_grace.personnel_user schema on 2026-04-04

CREATE TABLE IF NOT EXISTS `personnel_user` (
  `_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '记录ID，如 personnel-101',
  `person_id` int unsigned NOT NULL COMMENT '人员编号',
  `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '姓名',
  `nickname` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '昵称',
  `gender` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '性别',
  `age` tinyint unsigned DEFAULT NULL COMMENT '年龄',
  `mobile` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '手机号',
  `id_card_no` varchar(18) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '身份证号',
  `mbti` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'MBTI',
  `native_place` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '籍贯',
  `profession` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '职业',
  `church` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '教会/团契',
  `faith_duration` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '信主时长',
  `referrer` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '推荐人',
  `self_introduction` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '自我介绍',
  `relationship_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '感情状态',
  `travel_mode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '出行方式',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '地址',
  `family_overview` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '家庭概况',
  `review_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT '审核状态',
  `reviewer` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '审核人',
  `passcode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '邀请码',
  `user_role` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '用户角色',
  `personal_photo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '头像地址',
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '绑定用户ID',
  `private_message_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '私信额度',
  `heart_message_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '心动消息额度',
  `remaining_heart_value` int unsigned NOT NULL DEFAULT '0' COMMENT '剩余心动值',
  `remaining_mbti_test_count` int NOT NULL DEFAULT '0' COMMENT '剩余MBTI测试次数',
  `submitted_at` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '提交时间(ISO8601)',
  `updated_at` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '更新时间(ISO8601)',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '软删除',
  PRIMARY KEY (`_id`),
  UNIQUE KEY `uk_personnel_user_person_id` (`person_id`),
  UNIQUE KEY `uk_personnel_user_mobile` (`mobile`),
  UNIQUE KEY `uk_personnel_user_passcode` (`passcode`),
  KEY `idx_personnel_user_review_status` (`review_status`),
  KEY `idx_personnel_user_user_role` (`user_role`),
  KEY `idx_personnel_user_user_id` (`user_id`),
  KEY `idx_personnel_user_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人员档案(来源buildSeedPersonnel)';


INSERT INTO `personnel_user` (
  `_id`, `person_id`, `name`, `nickname`, `gender`, `age`, `mobile`,
  `id_card_no`, `mbti`, `native_place`, `profession`, `church`,
  `faith_duration`, `referrer`, `self_introduction`, `relationship_status`,
  `travel_mode`, `address`, `family_overview`, `review_status`, `reviewer`,
  `passcode`, `user_role`, `personal_photo`, `user_id`,
  `private_message_quota`, `heart_message_quota`, `remaining_heart_value`,
  `remaining_mbti_test_count`, `submitted_at`, `updated_at`, `is_deleted`
) VALUES
  (
    'personnel-201', 201, '测试同工', '同工', '男', 26, '15300002001',
    '350123200001010011', 'ENTO', '福建福州', '教培', '晨曦团契',
    '从小', '系统导入', '测试同工账号', '未婚单身',
    '地铁', '福建省福州市晋安区', '测试家庭信息', 'approved', '系统',
    'apple1001', 0, '', 'test-user-201',
    2, 3, 3,
    0, '2026-04-02T00:00:00.000Z', '2026-04-04T02:12:47.504Z', 0
  ),
  (
    'personnel-202', 202, '测试管理员', '管理员', '男', 28, '15300002002',
    '350123200001010022', 'ENTJ', '福建福州', '系统管理', '晨曦团契',
    '10年', '系统导入', '测试管理员账号', '未婚单身',
    '自驾', '福建省福州市鼓楼区', '测试家庭信息', 'approved', '系统',
    'banana1002', 2, '', 'test-user-202',
    4, 5, 5,
    0, '2026-04-02T00:00:00.000Z', '2026-04-02T00:00:00.000Z', 0
  ),
  (
    'personnel-203', 203, '测试超级管理员', '超管', '男', 30, '15300002003',
    '350123200001010033', 'INTJ', '福建福州', '平台运维', '晨曦团契',
    '20年', '系统导入', '测试超级管理员账号', '未婚单身',
    '自驾', '福建省福州市台江区', '测试家庭信息', 'approved', '系统',
    'orange1003', 3, '', 'test-user-203',
    6, 6, 6,
    0, '2026-04-02T00:00:00.000Z', '2026-04-02T00:00:00.000Z', 0
  )
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `nickname` = VALUES(`nickname`),
  `gender` = VALUES(`gender`),
  `age` = VALUES(`age`),
  `mobile` = VALUES(`mobile`),
  `id_card_no` = VALUES(`id_card_no`),
  `mbti` = VALUES(`mbti`),
  `native_place` = VALUES(`native_place`),
  `profession` = VALUES(`profession`),
  `church` = VALUES(`church`),
  `faith_duration` = VALUES(`faith_duration`),
  `referrer` = VALUES(`referrer`),
  `self_introduction` = VALUES(`self_introduction`),
  `relationship_status` = VALUES(`relationship_status`),
  `travel_mode` = VALUES(`travel_mode`),
  `address` = VALUES(`address`),
  `family_overview` = VALUES(`family_overview`),
  `review_status` = VALUES(`review_status`),
  `reviewer` = VALUES(`reviewer`),
  `passcode` = VALUES(`passcode`),
  `user_role` = VALUES(`user_role`),
  `personal_photo` = VALUES(`personal_photo`),
  `user_id` = VALUES(`user_id`),
  `private_message_quota` = VALUES(`private_message_quota`),
  `heart_message_quota` = VALUES(`heart_message_quota`),
  `remaining_heart_value` = VALUES(`remaining_heart_value`),
  `remaining_mbti_test_count` = VALUES(`remaining_mbti_test_count`),
  `submitted_at` = VALUES(`submitted_at`),
  `updated_at` = VALUES(`updated_at`),
  `is_deleted` = VALUES(`is_deleted`);
